include:
  - project: "Laboratory/Evergreen/DevOpsRepo"
    ref: main
    file:
      - "Templates/testcontainers-template.yml"
      - "Templates/tests-jacoco-template.yml"
      - "Templates/tests-sonar-template.yml"
      - "Templates/kaniko-build-template.yml"

stages:
  - test
  - build
  - deploy

test-testcontainers:
  extends: .test-testcontainers
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

Tests:
  stage: test
  extends: .test-jacoco 
  needs:
    - job: test-testcontainers # Используем шаблон Jacoco для тестов  # Выполняем только после завершения test-testcontainers
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

Tests:sonarqube:
  stage: test
  extends: .test-sonar  # Используем шаблон SonarQube для анализа
  needs:
    - job: Tests  # Выполняем только после завершения Tests
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

Build:
  stage: build
  variables:
    IMAGE_NAME: ${CI_PROJECT_NAME}
  extends: .kaniko_build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"

deploy:
  stage: deploy
  image: 
    name: alpine/k8s:1.25.13
    entrypoint: [""]
  script:
    - kubectl config get-contexts
    - mkdir -p /root/.kube
    - echo "${KUBE_CONFIG}" > /root/.kube/config
    - chmod 600 /root/.kube/config
    - kubectl config get-contexts
    - kubectl apply -f ./k8s/ -n dev
  only:
    - develop
