syntax = "proto3";

option java_multiple_files = true;
option java_package = "aston.lab.clientserver.grpc";
option java_outer_classname = "ClientProto";

package client;

service ClientService {
  rpc CreateClient (CreateClientRequest) returns (ClientResponse);
  rpc GetClient (GetClientRequest) returns (ClientResponse);
  rpc UpdateClient (UpdateClientRequest) returns (ClientResponse);
  rpc DeleteClient (DeleteClientRequest) returns (DeleteClientResponse);
}

message CreateClientRequest {
  string name = 1;
  string email = 2;
}

message GetClientRequest {
  int32 id = 1;
}

message UpdateClientRequest {
  int32 id = 1;
  string name = 2;
  string email = 3;
}

message DeleteClientRequest {
  int32 id = 1;
}

message ClientResponse {
  int32 id = 1;
  string name = 2;
  string email = 3;
}

message DeleteClientResponse {
  bool success = 1;
}