apiVersion: v1
kind: Secret
metadata:
  name: client-postgres-secret
  namespace: dev
type: Opaque
data:
  POSTGRES_DB: Y2xpZW50X2Ri
  POSTGRES_USER: Y2xpZW50X3VzZXI=
  POSTGRES_PASSWORD: c2VjdXJlX3Bhc3N3b3JkMTIz
